# Generated by Django 4.2.1 on 2023-05-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restAddress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restName',
        ),
    ]
